{
  "apiVersion": 1,
  "datasources": [
    {
      "access": "proxy",
      "editable": true,
      "jsonData": {
        "timeInterval": "15s"
      },
      "name": "Prometheus",
      "orgId": 1,
      "type": "prometheus",
      "url": "http://prometheus:9090",
      "version": 1
    },
    {
      "access": "proxy",
      "editable": true,
      "jsonData": {
        "timeInterval": "15s"
      },
      "name": "Loki",
      "orgId": 1,
      "type": "loki",
      "url": "http://loki:3100",
      "version": 1
    }
  ]
}